services:
  - type: web
    name: studybuddyfinder-api
    env: node
    region: oregon
    plan: free
    rootDir: be
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: 10000
